"""Agent 3 — Mapping Strategist: the AI brain (Gemini) that decides the plan.

Uses the Gemini API (google-genai SDK) instead of Anthropic. When no
GEMINI_API_KEY is configured, or the model output cannot be parsed, a
deterministic fallback planner built on the type-coercion table produces the
plan so the pipeline still completes (with a warning logged).
"""
from __future__ import annotations

import json
import re
from typing import Any

from ..config import get_settings
from ..utils.logger import job_logger
from ..utils.type_mapper import TYPE_COERCION_MAP, map_type, normalise_type

AGENT_NAME = "mapping_strategist"

SYSTEM_PROMPT = """
You are a database migration strategist. You will receive a source database schema,
a data profile, and source/target database types. You must output a detailed migration plan
as valid JSON only. No prose. No markdown. No explanation outside the JSON structure.

The JSON must have this exact top-level shape:
{
  "tables": [
    {
      "source_table": "<name>",
      "target_table_name": "<name>",
      "column_mappings": [
        {"source_column": "...", "target_column": "...", "source_type": "...",
         "target_type": "...",
         "transformation": null | "to_boolean" | "to_int" | "to_float" |
                           "to_string" | "parse_datetime" | "json_stringify"}
      ],
      "transformation_rules": ["<free text rules>"],
      "relationship_handling": "<how FKs/references are handled in target>",
      "warnings": ["<data quality issues or semantic uncertainties>"]
    }
  ],
  "execution_order": ["<table names in FK-safe insert order>"],
  "global_warnings": ["..."]
}

"transformation" MUST be null or one of the listed operation names — the
executor interprets these mechanically; free-text transformations are ignored.
"""


class MappingStrategist:
    def __init__(self, schema_snapshot: dict[str, Any], data_profile: dict[str, Any],
                 source_db_type: str, target_db_type: str, user_options: dict[str, Any],
                 job_id: str, log_sink=None):
        self.schema = schema_snapshot
        self.profile = data_profile
        self.source_db_type = source_db_type
        self.target_db_type = target_db_type
        self.options = user_options
        self.job_id = job_id
        self.log = job_logger(__name__, job_id, AGENT_NAME)
        self.log_sink = log_sink
        self.settings = get_settings()

    async def _emit(self, level: str, message: str, metadata: dict[str, Any] | None = None):
        self.log.info(message)
        if self.log_sink:
            await self.log_sink(level, AGENT_NAME, message, metadata or {})

    async def run(self) -> dict[str, Any]:
        if self.settings.gemini_api_key:
            try:
                plan = await self._generate_with_gemini()
                plan = self._sanity_check(plan)
                await self._emit("success", "AI migration plan generated by Gemini.",
                                 {"model": self.settings.gemini_model})
                return plan
            except Exception as e:  # noqa: BLE001 — always fall back, never silently
                await self._emit("warning",
                                 f"Gemini planning failed ({e}); using deterministic fallback plan.")
        else:
            await self._emit("warning",
                             "GEMINI_API_KEY not configured — using deterministic fallback plan.")
        plan = self.fallback_plan()
        await self._emit("success", "Fallback migration plan generated from type-coercion rules.")
        return plan

    # ── Gemini call ────────────────────────────────────────────────
    async def _generate_with_gemini(self) -> dict[str, Any]:
        from google import genai
        from google.genai import types

        client = genai.Client(api_key=self.settings.gemini_api_key)
        user_message = f"""
Source database type: {self.source_db_type}
Target database type: {self.target_db_type}
User options: {json.dumps(self.options)}

SOURCE SCHEMA:
{json.dumps(self.schema, indent=2, default=str)}

DATA PROFILE:
{json.dumps(self.profile, indent=2, default=str)}

TYPE COERCION REFERENCE:
{json.dumps(TYPE_COERCION_MAP, indent=2)}

Generate the migration plan now. Output JSON only.
"""
        response = await client.aio.models.generate_content(
            model=self.settings.gemini_model,
            contents=user_message,
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPT,
                response_mime_type="application/json",
                max_output_tokens=8096,
            ),
        )
        raw = response.text or ""
        return self._parse_json(raw)

    @staticmethod
    def _parse_json(raw: str) -> dict[str, Any]:
        raw = raw.strip()
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            match = re.search(r"\{.*\}", raw, re.DOTALL)
            if match:
                return json.loads(match.group(0))
            raise

    def _sanity_check(self, plan: dict[str, Any]) -> dict[str, Any]:
        if "tables" not in plan or not isinstance(plan["tables"], list):
            raise ValueError("plan missing 'tables' list")
        plan.setdefault("execution_order",
                        [t.get("source_table") for t in plan["tables"]])
        plan.setdefault("global_warnings", [])
        plan.setdefault("summary", self._summary_line(len(plan["tables"])))
        source_tables = self.schema.get("tables", {})
        for t in plan["tables"]:
            t.setdefault("estimated_rows",
                         source_tables.get(t.get("source_table"), {}).get("row_count", 0))
        return plan

    def _summary_line(self, table_count: int) -> str:
        total = sum(t.get("row_count", 0)
                    for t in self.schema.get("tables", {}).values())
        return (f"Migrate {table_count} table(s) (~{total} rows) from "
                f"{self.source_db_type} to {self.target_db_type}.")

    # ── Deterministic fallback ─────────────────────────────────────
    def fallback_plan(self) -> dict[str, Any]:
        skip = set(self.options.get("skip_tables", []))
        tables_out = []
        source_tables = self.schema.get("tables", {})
        for name, info in source_tables.items():
            if name in skip:
                continue
            mappings = []
            warnings = []
            for col in info.get("columns", []):
                canonical = normalise_type(self.source_db_type, col["type"])
                tgt = map_type(self.source_db_type, self.target_db_type, col["type"])
                transformation = None
                prof = (self.profile.get("tables", {}).get(name, {})
                        .get("columns", {}).get(col["name"], {}))
                if prof.get("implicit_boolean") and canonical != "boolean":
                    transformation = "to_boolean"
                if prof.get("pii_suspected"):
                    warnings.append(f"Column '{col['name']}' looks like PII — verify handling.")
                mappings.append({
                    "source_column": col["name"],
                    "target_column": col["name"],
                    "source_type": col["type"],
                    "target_type": tgt,
                    "transformation": transformation,
                })
            tables_out.append({
                "source_table": name,
                "target_table_name": name,
                "estimated_rows": info.get("row_count", 0),
                "column_mappings": mappings,
                "transformation_rules": [],
                "relationship_handling": (
                    "FK columns copied as plain values; constraints not recreated by fallback planner."
                    if info.get("foreign_keys") else "no relationships"),
                "warnings": warnings,
            })
        return {
            "summary": self._summary_line(len(tables_out)),
            "tables": tables_out,
            "execution_order": self._fk_safe_order(
                [t["source_table"] for t in tables_out], source_tables),
            "global_warnings": ["Plan generated by deterministic fallback (no AI reasoning)."]
            if not self.settings.gemini_api_key else [],
        }

    @staticmethod
    def _fk_safe_order(names: list[str], tables: dict[str, Any]) -> list[str]:
        """Topological sort so referenced tables load before referencing ones."""
        remaining = list(names)
        ordered: list[str] = []
        while remaining:
            progressed = False
            for name in list(remaining):
                deps = {fk["ref_table"] for fk in tables.get(name, {}).get("foreign_keys", [])}
                if deps.issubset(set(ordered) | {name}) or deps.isdisjoint(remaining):
                    ordered.append(name)
                    remaining.remove(name)
                    progressed = True
            if not progressed:  # FK cycle — append the rest as-is
                ordered.extend(remaining)
                break
        return ordered
